# Generated by Django 6.0 on 2026-01-12 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "split",
                    models.CharField(
                        choices=[
                            ("Full_BODY", "Full Body"),
                            ("UPPER_LOWER", "Upper / Lower"),
                            ("PPL", "Push / Pull / Legs"),
                        ],
                        default="FULL_BODY",
                        max_length=20,
                    ),
                ),
                ("days_per_week", models.PositiveIntegerField(default=3)),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("GYM", "Gym"),
                            ("HOME", "Home"),
                            ("BODYWEIGHT", "Bodyweight"),
                        ],
                        default="GYM",
                        max_length=20,
                    ),
                ),
                (
                    "focus",
                    models.CharField(
                        choices=[
                            ("HYPERTROPHY", "Hypertrophy"),
                            ("STRENGTH", "Strength"),
                            ("FAT_LOSS", "Fat Loss"),
                            ("GENERAL", "General Fitness"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "use",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
