# Generated by Django 6.0 on 2026-01-12 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout_preference", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutpreference",
            old_name="use",
            new_name="user",
        ),
    ]
