# Generated by Django 6.0 on 2025-12-21 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("height_cm", models.PositiveIntegerField()),
                ("weight_kg", models.PositiveIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=10
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("BULKING", "Bulking"),
                            ("CUTTING", "Cutting"),
                            ("MAINTAINING", "Maintaining"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("SEDENTARY", "Sedentary"),
                            ("MODERATE", "Moderate"),
                            ("ACTIVE", "Active"),
                        ],
                        default="SEDENTARY",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
